package io.vertigo.chatbot.designer.domain.analytics;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class RequestExport implements DtObject {
	private static final long serialVersionUID = 1L;

	private java.time.Instant date;
	private Double recognized;
	private Double unrecognized;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Date'.
	 * @return Instant date
	 */
	@Field(smartType = "STyInstant", label = "Date")
	public java.time.Instant getDate() {
		return date;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Date'.
	 * @param date Instant
	 */
	public void setDate(final java.time.Instant date) {
		this.date = date;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Number of recognized'.
	 * @return Double recognized
	 */
	@Field(smartType = "STyDouble", label = "Number of recognized")
	public Double getRecognized() {
		return recognized;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Number of recognized'.
	 * @param recognized Double
	 */
	public void setRecognized(final Double recognized) {
		this.recognized = recognized;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Number of unrecognized'.
	 * @return Double unrecognized
	 */
	@Field(smartType = "STyDouble", label = "Number of unrecognized")
	public Double getUnrecognized() {
		return unrecognized;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Number of unrecognized'.
	 * @param unrecognized Double
	 */
	public void setUnrecognized(final Double unrecognized) {
		this.unrecognized = unrecognized;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
